
<?php
function calendar_update_menu() {

  $items = array();

  $items['calendar/update'] = array(
    'title' => 'Calendar Updater',
    'page callback' => 'calendar_update_get_by_category_id',
    'access arguments' => array('calendar update'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function calendar_update_permission() {
  $perms = array(
    'calendar update' => array(
      'title' => t('Calendar Update'),
    )
  );
  return $perms;
}

function calendar_update_get_by_category_id($str_class, $str_date='novalue', $curr_date){
  $arr_months = array('Jan'=>'01', 'Feb'=>'02', 'Mar'=>'03', 'Apr'=>'04', 'May'=>'05', 'Jun'=>'06', 'Jul'=>'07', 'Aug'=>'08', 'Sep'=>'09', 'Oct'=>'10', 'Nov'=>'11', 'Dec'=>'12' );
  $items = '';
  $str_day = '';
  // pull day of week from class fc-day1
  $int_day = preg_match('/fc-day(.?)/', $str_class, $str_dayofwk_matches);
  // pull calendar year
  //$int_year = preg_match('/^(.*)\-.*(\d{4})/', $str_date, $str_yr_matches);
  //pull start of calendar week from weekly header 'Jul 3 - 9 2011'
  $int_year = preg_match('/^(\w{3}) (\d{1,2}).*(\d{4})$/', urldecode($str_date), $str_yr_matches);

  $viewName = 'fullcalendar';
  $displayId = 'calendar_day_block';
  $args = date('Y-m-d', mktime(0, 0, 0, $arr_months[$str_yr_matches[1]], ($str_yr_matches[2] + $str_dayofwk_matches[1]), $str_yr_matches[3]));

  $res = views_embed_view($viewName, $displayId, $args);
  $memo = $str_dayofwk_matches[1] . ' | ' . implode('@@', $str_yr_matches) . ' | ' .$args;
  //$memo = createWeekView($args);
  // create a JSON object. The object will contain a property named ÒproductsÓ that will be set with the $items variable.
  return drupal_json_output(
    array(
      'products' => $res,
      'memo' => $memo
    )
  );
  exit;
}

function createWeekView($str_date){
  if (!$str_date){ $date = date('Y-m-d'); }
  $yr_num = date("Y", strtotime($str_date));
  $wk_num = date("W", strtotime($str_date));
  $sun_target_week = date('m/d/Y', strtotime($yr_num.'W'.$wk_num.'0'));
  return $sun_target_week;
}

function calendar_update_theme() {
   return array(
      'calendar_update_javascript' => array(
         'arguments' => array(),
      ),
   );
}

function calendar_update_init() {
  theme('calendar_update_javascript');
}

function theme_calendar_update_javascript() {
  drupal_add_js(drupal_get_path('module', 'calendar_update') . '/calendar_update.js');
}

