<?php



/**
* Implementation of hook_form_alter().  
* This modifies the default login form of each moderated content type.
*/

function coa_login_form_alter(&$form, $form_state, $form_id) {
   // a switch is used because you may want to alter more than
   // one form and it is easy to add a new case for each form.
   switch ($form_id) {
     // This is our form ID.
     case 'user_login':
     case 'user_login_block':
     		$form['name']['#description'] = t("Enter your City of Austin network user name to access the AustinGO site.");
     		$form['tos'] = array(
						'#title' => t('Terms of Service'),
						'#type' => 'item',
						'#description' => t('Lorem ipsum dolor sit amet, consectetuer adipiscing elit, 
											sed diam nonummy nibh euismod tincidunt ut laoreet dolore 
											magna aliquam erat volutpat. Ut wisi enim ad minim veniam, 
											quis nostrud exerci tation ullamcorper suscipit lobortis nisl 
											ut aliquip ex ea commodo consequat. Duis autem vel eum iriure 
											dolor in hendrerit in vulputate velit esse molestie consequat.'),
     		            );
     		$form['#redirect'] = 'admin/workbench';
            //dpm($form, "form");             
      break;
   };
   
};

/*
* Implementation of hook_user()
*/
function coa_login_user($op){
    //go to current node after login
    //$alias = drupal_get_path_alias($_GET['q']);
    
    //go to workbengh
    $alias = 'admin/workbench';
    
    if ( $op == "login" ){
       drupal_goto( "http://" . $_SERVER['HTTP_HOST'].'/'.$alias );
    }
}