<?php

/**
* Implementation of hook_menu().
*/
function coa_contact_information_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'coa_contact_information/myautocomp',
      'title' => t('AutoComplete Menu'),
      'callback' => 'coa_contact_information_autocomp',
      'access' => TRUE
    );
  }
  return $items;
}


/**
* Retrieve a pipe delimited string of autocomplete suggestions for existing users
*/
function coa_contact_information_autocomp($string) {
  $matches = array();
  $result = db_query_range("SELECT name FROM {users} WHERE LOWER(name) LIKE LOWER('%s%%')", $string, 0, 10);
  while ($user = db_fetch_object($result)) {
    $matches[$user->name] = check_plain($user->name);
  }
  print drupal_to_js($matches);
  exit();
}



/**
* Implementation of hook_form_alter().  
* This modifies the default login form of each moderated content type.
*/

function coa_contact_information_form_alter(&$form, $form_state, $form_id) {
   
   switch ($form_id) {
 
     case 'contact_information_node_form':
          //dpm($form, 'form');
          //dpm($form_state, 'form_state');
          $form['field_contact_name_or_title']['#type'] = 'hidden';
          $form['field_contact_name_or_title']['und']['#required'] = FALSE;  //'und' is LANGUAGE_NONE
          $form['field_contact_name_or_title']['en']['#required'] = FALSE;
          
          $form['#submit'][] = 'coa_contact_information_form_submit';
		  //$form['actions']['submit']['#submit'][] = 'coa_contact_information_form_submit';
		  
     break;  
   };
   
};

/*
* Implementation of hook_user()
*/
function coa_contact_information_form_submit($form, &$form_state){
  
   if (empty($form_state['values']['field_contact_full_name']['en'][0]['value'])) {
       $result = array('value' => $form_state['values']['title']);
       $form_state['values']['field_contact_name_or_title']['en'][0] = $result;    
     } else {
       $form_state['values']['field_contact_name_or_title'] = $form_state['values']['field_contact_full_name']; 
   };
   // reset pathauto
   $form_state['values']['path']['alias'] = '';
   $form_state['values']['path']['pathauto'] = 1;
}

